#!/usr/bin/env bash
CWD=$(pwd)
cd src || exit

echo ""
echo "Looking for differences with remotes ..."

# fetch from all repos first
for d in $(find . -mindepth 1 -maxdepth 1 -type d | sort -t '\0' -n)
do
    cd "$d" || exit
    git fetch
    cd ..
done

# Generate the md
echo ""
echo "### $(date +%F)"
for d in $(find . -mindepth 1 -maxdepth 1 -type d | sort -t '\0' -n)
do
    cd "$d" || exit
    REPOS_NAME="${d#*\/}"

    # Get the url of the repository
    URL=$(git remote get-url origin)
    URL="${URL%\.git}"
    URL="${URL#*:}"
    URL="${URL#*github\.com/}"

    # Get the current and origin's head commit hash
    BRANCH=$(git rev-parse --abbrev-ref HEAD)
    HASH_LOCAL=$(git rev-parse HEAD | cut -c 1-9)
    HASH_LOCAL_FULL=$(git rev-parse HEAD)
    HASH_HEAD=$(git rev-parse origin/"$BRANCH" | cut -c 1-9)
    HASH_HEAD_FULL=$(git rev-parse origin/"$BRANCH")

    if [ "$HASH_HEAD" != "$HASH_LOCAL" ]; then
        # with diff comparison
        echo "- [\`$REPOS_NAME $HASH_LOCAL\`](https://github.com/$URL/commit/$HASH_LOCAL_FULL) [\`diff $HASH_LOCAL...$BRANCH@$HASH_HEAD\`](https://github.com/$URL/compare/$HASH_LOCAL_FULL...$HASH_HEAD_FULL)"
    else
        # without diff comparison
        echo "- [\`$REPOS_NAME $HASH_LOCAL\`](https://github.com/$URL/commit/$HASH_LOCAL_FULL)"
    fi

    cd ..

done

cd "$CWD" || exit

echo ""
echo "#### Buildout"
echo "\`\`\`"
./versions_buildout
echo "\`\`\`"
echo ""
