---

- debug:
    msg: "******************** CUSTOM PRE [START] *******************"

- name: "Cleanup nginx's enabled sites, if any"
  shell: "rm -f /etc/nginx/sites-enabled/*"
  become: yes

- name: "Generate deploy key for bes.nauru.lims repos"
  user:
    name: "{{user}}"
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: "{{ plone_target_path }}/.ssh/{{ item }}"
  loop: "{{ ssh_keys }}"

- name: "Check SSH public keys"
  command: "cat {{ plone_target_path }}/.ssh/{{ item }}.pub"
  register: cat
  changed_when: False
  loop: "{{ ssh_keys }}"

- name: "Print SSH public keys"
  debug:
    var: cat.stdout

- name: "Wait for user to copy SSH public key"
  pause:
    prompt: "Please, add the SSH public key above to the GitHub account ..."

- name: "Configure Secure Access to remote source repos"
  template:
    src: templates/ssh_config.conf.j2
    dest: "{{ plone_target_path }}/.ssh/config"
    force: no
    owner: senaite
    group: senaite
    mode: 0600
  tags:
    - senaite-custom

- name: "Register Github to the list of known hosts"
  shell: "ssh -T -i ~/.ssh/{{ ssh_key_filename }} -oStrictHostKeyChecking=accept-new git@ssh.github.com"
  become_user: "{{ user }}"
  ignore_errors: "yes"
  loop: "{{ ssh_keys }}"
  tags:
    - senaite-custom

- name: "Add SWAP configuration"
  template:
    src: templates/90-senaite-sysctl.conf.j2
    dest: "/etc/sysctl.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - senaite-custom

- debug:
    msg: "******************** CUSTOM PRE [DONE] ********************"
